#%RAML 1.0 NamedExample
value:
  customername: Max
  moviename: Jalsa
  city: Pune
  theater: City Pride
  date: 2021-10-21
  showtime: 04:30:00
  price: 50.00
  totalprice: 150.00
  numberofseats: 3
  offercode: FIRST3